INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (46867,-12292 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56611,-12292 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56612,-12292 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56613,-12292 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56614,-12292 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (46867,-94405 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56611,-94405 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56612,-94405 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56613,-94405 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (56614,-94405 ,0,'Wrecking Crew proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (29593,-12292,0,'Enraged Protection proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (29593,-94405,0,'Enraged Protection proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (29594,-12292,0,'Enraged Protection proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (29594,-94405,0,'Enraged Protection proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12317,-12292,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12317,-94405,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13045,-12292,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13045,-94405,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13046,-12292,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13046,-94405,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13047,-12292,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13047,-94405,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13048,-12292,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (13048,-94405,0,'Enrage proc deletes Deathwish');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-29593,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-29594,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-57514,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-57516,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-12317,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-13045,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-13046,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-13047,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-13048,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-12880,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-14201,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-14202,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-14203,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-14204,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-46867,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-56611,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-56612,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-56613,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (12292,-56614,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-29593,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-29594,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-57514,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-57516,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-12317,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-13045,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-13046,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-13047,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-13048,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-12880,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-14201,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-14202,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-14203,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-14204,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-46867,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-56611,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-56612,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-56613,0,'Deathwish proc deletes other Enrages');
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES (94405,-56614,0,'Deathwish proc deletes other Enrages');



